Extend options
jenkinsci/jenkinsfile-runner pull request #203
Opened 2019-10-17 13:31 UTC by rinckm

Add additional options to specify
- job name
- build number
- cause
We want to be able to specify meaningful values here so they can be used in some plugins.

2019-10-17 22:10 UTC, oleg-nenashev requested changes
Thanks! Job Name and Build Number sound about right, but I am not sure about `cause`. Introducing a new instance type in the Jenkinsfile Runner would do the job for some edge cases, but I would rather expect common causes to be set, e.g. SCM cause. Having a custom cause type limits options for it to be consumed by plugins. Would be great to have more justification for that before merging

2019-10-17 22:10 UTC, oleg-nenashev commented on bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
> +    @Option(name = "-b", aliases = { "--build-number"}, usage = "BuildNumber of the run")
```suggestion
    @Option(name = "-b", aliases = { "--build-number"}, usage = "Build number of the run")
```

2019-10-17 22:10 UTC, oleg-nenashev commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
> +        List<Action> workflowActionsList = new ArrayList<Action>(3);
```suggestion
        List<Action> workflowActionsList = new ArrayList<>(3);
```

2019-10-17 22:10 UTC, oleg-nenashev commented on README.md
> +                               build log and is availabled to plug-ins and pipeline steps.
```suggestion
                               build log and becomes available to plug-ins and pipeline steps.
```

2019-10-18 11:19 UTC, rinckm commented
> 
> 
> Thanks! Job Name and Build Number sound about right, but I am not sure about `cause`. Introducing a new instance type in the Jenkinsfile Runner would do the job for some edge cases, but I would rather expect common causes to be set, e.g. SCM cause. Having a custom cause type limits options for it to be consumed by plugins. Would be great to have more justification for that before merging

I had a look to the existing causes but from my point of view they don't really match.
For the SCMTriggerCause we would need to have a polling log file.
If we take UserIdCause we would need to create a user for each execution of the Jenkinsfile Runner to avoid problems.
The RemoteCause comes close but I would only define the note but no host.
We could rename the Cause to NoteCause with 'Started with note %s' as description.
We could also name the Cause FileRunnerCause.
What do you think?

2019-10-18 13:57 UTC, rinckm commented
I cannot reproduce the failing check locally. Looks like an infrastructure error to me.

2019-10-18 14:00 UTC, oleg-nenashev commented
yes, infra and Jenkinsfile Runner CI are quite unstable.
I agree with having an explicit JFR-specific cause as long as it is not
injected by default



On Fri, Oct 18, 2019 at 3:57 PM Matthias Rinck <notifications@github.com>
wrote:

> I cannot reproduce the failing check locally. Looks like an infrastructure
> error to me.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkinsfile-runner/pull/203?email_source=notifications&email_token=AAW4RIHZFCVM3MWSHJA54GLQPG6ETA5CNFSM4JBZU5C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBURY2Y#issuecomment-543759467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW4RIAERHQPJ7ZK3SFOW6LQPG6ETANCNFSM4JBZU5CQ>
> .
>

2019-10-19 08:44 UTC, oleg-nenashev requested changes
Requesting the change as discussed above, but this is mostly ready to go

2019-10-21 08:42 UTC, rinckm commented
This change if fully backward compatible. If no --cause cli option is set the code works as before.

2019-10-21 08:47 UTC, rinckm commented
Pipeline: 
node {
        stage('Build') {
              echo currentBuild.getBuildCauses().toString()
            }
    }
---
--cause 'foo'
-> [{"_class":"io.jenkins.jenkinsfile.runner.FileRunnerCause","shortDescription":"Started by foo"}]
---
-- cause '' 
-> []
---
No cause cli option set
-> []

2019-10-21 11:47 UTC, oleg-nenashev approved these changes
apart from the class naming, it is ready to go imho.
Class name can be changed later, but it would be great to land it so that we close this story

2019-10-21 11:47 UTC, oleg-nenashev commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/FileRunnerCause.java
> +class FileRunnerCause extends hudson.model.Cause {
```suggestion
class JenkinsfileRunnerCause extends hudson.model.Cause {
```

2019-10-21 11:48 UTC, oleg-nenashev commented on README.md
> + -n (--job-name) VAL         : Name of the job the run belongs to, defaults to 'job'
Will create a follow-up task to support folders

2019-10-21 14:21 UTC, rinckm commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/FileRunnerCause.java
> +class FileRunnerCause extends hudson.model.Cause {
Class name is fixed now.

2019-10-21 14:53 UTC, oleg-nenashev approved these changes

2019-10-21 14:54 UTC, rinckm commented
Just added 7f4ab782f7ae6a9ab82b5853d29aab23933fcb6a. Is this OK too?

2019-10-21 14:57 UTC, rinckm commented
Only fixed the commit message from  7f4ab78 to ced2c76.
I'm ready now.

2019-10-21 18:54 UTC, merged

2019-10-21 18:55 UTC, oleg-nenashev commented
Thanks @rinckm! I hope to cut a new release within few days