Allow for passing worfklow job parameters
jenkinsci/jenkinsfile-runner pull request #26
Opened 2018-05-31 03:20 UTC by toshke

## Feature description

Idea is that `jenkinsfile-runner` can be used for testing of shared libraries with different parameters passed to test pipelines, e.g. same pipeline using shared library functionality should fail or succeed, depending on parameters passed to pipeline job.

Also, another CLI switch (`-ns or  --no-sandbox`) is added in order to disable sandboxing. Default behaviour is not changed however. 

## Implementation notes

Parameters are passed in following format
`-params="param1=value1&params2=value2"`

CLI parsing is done in such way that parameters are separated by ampersand symbol `&`, hence disallowing this symbol to be used in parameter value. There is safety check  (e.g. passing `-params=value` will result in appropriate error message)

```
root@194280c42eb8:/src# /app/bin/jenkinsfile-runner -w /app/jenkins -p /usr/share/jenkins/ref/plugins -f test -params value
Exception in thread "main" java.lang.RuntimeException: parameters massed be passed in param1=value1&param2=value2 format
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.lambda$postConstruct$0(Bootstrap.java:136)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.postConstruct(Bootstrap.java:135)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:81)

```

2018-10-30 15:51 UTC, oleg-nenashev commented
@toshke Is it still actual? I'd guess so

2018-10-31 21:26 UTC, toshke commented
@oleg-nenashev it was couple months ago when PR was raised,  I would expect it is compatible with current code as well as there are no conflicts. BTW,  happy to see some activity on this repo, would be happy to contribute more

2018-11-01 05:32 UTC, oleg-nenashev reviewed
I would create another section in README, e.g. "Passing parameters". The rest lgtm

2019-01-26 03:52 UTC, rcarson commented
Is this PR dead? Any chance of reviving it? 

Could I also suggest instead of passing an ampersand delimited list of options, instead `-a` and `--arg` populate a list. Providing the same argument (`-a` or `--arg`) multiple times to jenkinsfile-runner, would update the list of parameter key/value pairs and it would also align more with other CLI tools (ie, docker).

2019-01-28 07:52 UTC, toshke commented
@rcarson I haven't been active with work on this PR recent weeks, passing of arguments was implemented differently when PR was created, as project had very bare version (manual) of arg parsing at the moment. I'll try and rebase this work with work on the master this week, and add some doco around the feature.

2019-01-29 17:59 UTC, rcarson commented
Thank you, I appreciate it.

2019-01-31 09:47 UTC, toshke commented
@rcarson  this PR has been rebased with latest `master` version. Also, requested changes for multiple `-a` cli switches have been implemented. I'll check on CI build later on, once results come in.

2019-01-31 09:55 UTC, toshke commented
@oleg-nenashev  parameters now have their own section within `README.md`

2019-02-04 08:27 UTC, oleg-nenashev requested changes
CI legitimately fails:

```
   8.015 [id=1]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (main/1) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.

java.lang.NullPointerException

	at io.jenkins.jenkinsfile.runner.Runner.run(Runner.java:40)

Caused: java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerLauncher.launch(JenkinsfileRunnerLauncher.java:126)

	at io.jenkins.jenkinsfile.runner.App.run(App.java:14)

	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.run(Bootstrap.java:192)

	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:85)

```

2019-02-04 08:28 UTC, oleg-nenashev commented on bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
> +    public Map<String,String> workflowParameters;
```suggestion
    @CheckForNull
    public Map<String,String> workflowParameters;
```

2019-02-04 08:28 UTC, oleg-nenashev commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
> +                new ParametersAction(bootstrap.workflowParameters
Needs null check here

2019-02-04 12:09 UTC, toshke commented on bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
> +    public Map<String,String> workflowParameters;
@oleg-nenashev   fixed, CI build completed with success.

2019-02-04 12:09 UTC, toshke commented
@oleg-nenashev  thanks for the review, I've incorporated your changes, and CI tests seem to have completed.

2019-02-04 12:29 UTC, oleg-nenashev reviewed
I highly recommend passing ParametersAction only when there are parameters to pass. Otherwise it may lead to various glitches, especially when building against older Jenkins versions.

Also I am not sure why FindBugs does not fail during the build. It should raise the flag in the current implementation AFAICT.

2019-02-04 12:40 UTC, toshke commented
@oleg-nenashev 

1. As for the FindBugs, it seems like the whole `Archive` stage has been commented out - https://github.com/jenkinsci/jenkinsfile-runner/blob/master/Jenkinsfile#L43

2. Requested changes for conditional passing of parameters action has been added

Not sure if you want all of these changes squashed into single commit, or while merging you can just squash merge?  PR seems to be still building / waiting for an executor at the time being.

2019-02-04 12:44 UTC, oleg-nenashev commented
> Not sure if you want all of these changes squashed into single commit, or while merging you can just squash merge? PR seems to be still building / waiting for an executor at the time being.

Thanks for asking. I can squash-merge, so no need to spend time on manually doing it

2019-02-04 13:42 UTC, varyvol approved these changes

2019-02-04 14:34 UTC, fcojfernandez approved these changes
LGTM.

2019-02-05 11:06 UTC, toshke commented
@oleg-nenashev CI seems to be reporting success. Unsure about `findBugs` stage though

2019-02-05 11:10 UTC, oleg-nenashev approved these changes
OK, let's merge as is. I will probably do some refactoring afterwards

2019-02-05 11:10 UTC, merged

2019-02-05 11:11 UTC, oleg-nenashev commented
Thanks @toshke ! It should land in the next release of Jenkinsfile Runner

2019-02-05 11:12 UTC, toshke commented
no probs - happy to contribute, thanks to @rcarson  for reviving the PR, it totally slipped from my radar.