Allow jenkinsfile-runner to integrate with the Jenkins Templating Engine
jenkinsci/jenkinsfile-runner pull request #477
Opened 2021-03-08 22:02 UTC by steven-terrana

## Integrate the Jenkins Templating Engine 

### Add JTE options to `PipelineRunOptions`

added a [ `-jte`, `--jenkins-templating-engine`] flag which tells jenkinsfile-runner to use the JTE pipeline definition provider. 

added a [ `-pc`, `--pipeline-configuration` ] flag which allows users to configure the path to a pipeline configuration file for JTE

### Add a JTE Pipeline Definition Provider

Added a `TemplatingEnginePipelineDefinitionProvider` that is able to instrument the `WorkflowJob` with a `FlowDefinition` form JTE. 

### Refactor SCM Credentials onto `SCMContainer`

To avoid code duplication, I refactored the code to add the `-scm` credential to the credential store onto helper functions on the `SCMContainer`.  This allowed the JTE Pipeline Definition Provider to integrate with the remote SCM functionality. 

## Open Questions

* Would it be possible to include this class as part of JTE instead of within the jenkinsfile-runner? Are `ExtensionPoint`s from plugins available to `Runner`?
* If it's possible to load the JTE Pipeline Definition extension point from the JTE plugin itself, then perhaps JTE should also contribute `PipelineRunOptions` by allowing plugins to inject command line options to jenkinsfile-runner. The benefits to this approach would be 3rd party plugins to be able to augment jenkinsfile-runner in isolation without needing to modify jenkinsfile-runner code. Thoughts?
* How would you recommend tests be added for validating JTE? I've done testing myself but i'm unsure how to add tests to a test suite to validate the JTE integration. 

## Checklist

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-03-08 22:09 UTC, oleg-nenashev requested changes
I am definitely +1 for adding the Jenkins Templating Engine support, but I am not sure about making it a hard requirement. My preference would be to evolve extensibility options so that the plugin becomes optional (see how Pipeline as YAML is implemented now).

Happy to introduce API plugins if needed

2021-03-08 22:13 UTC, steven-terrana commented
fully agree, i would prefer to remove `TemplateEnginePipelineDefinitionProvider` from jenkinsfile-runner altogether.  Need to test if the plugin extension point is resolvable from `Runner`. 

Ideally, jenkinsfile-runner shouldn't even need to know about JTE at all. 

I'll see if i can prototype:

1. putting the JTE pipeline definition in the JTE codebase itself rather than in the jenkinsfile-runner source code
2. coming up with an extension point to allow 3rd party plugins to augment jenkinsfile-runner's command line options

If [1] and [2] are possible, then jenkinsfile-runner could integrate without even knowing about JTE

2021-03-08 22:15 UTC, oleg-nenashev commented
> coming up with an extension point to allow 3rd party plugins to augment jenkinsfile-runner's command line options

Extension point won't be enough, because plugins and the Jenkins core are not even classloaded at that point when Slim packaging from https://github.com/jenkinsci/jenkinsfile-runner/tree/master/packaging-slim-parent-pom is used. It will require another extension mechanism.

2021-03-09 01:09 UTC, steven-terrana commented
set JTE to optional - did a search for `pipeline-as-yaml` and tried to match the dependency style everywhere so they're done the same way.

2021-03-15 14:48 UTC, oleg-nenashev requested changes
Looks good, but the optional exception loading will not work properly with the current implementation

2021-03-15 14:48 UTC, oleg-nenashev commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/TemplatingEnginePipelineDefinitionProvider.java
> +@Extension public class TemplatingEnginePipelineDefinitionProvider extends PipelineDefinitionProvider {
```suggestion
@Extension(optional = true)
public class TemplatingEnginePipelineDefinitionProvider extends PipelineDefinitionProvider {
```

2021-03-15 14:48 UTC, oleg-nenashev commented on payload/src/main/java/io/jenkins/jenkinsfile/runner/TemplatingEnginePipelineDefinitionProvider.java
> +
Needs static initializer which checks availability of the class within the plugin.
Otherwise the optional extension will be accepted

2021-03-27 21:04 UTC, steven-terrana commented
hey Oleg - checking in on this. Is there anything else i can do to help get this over the finish line?

2021-03-27 21:48 UTC, oleg-nenashev commented
I suppose the ball is on my side, sorry for the delay

2021-03-30 16:24 UTC, oleg-nenashev approved these changes
Works on my machine (c). Thanks a lot @steven-terrana ! Will try to release it this week

2021-03-30 16:24 UTC, merged