Fix demo/cwp-jdk11
jenkinsci/jenkinsfile-runner pull request #68
Opened 2019-02-11 17:06 UTC by fcojfernandez

After executing the demo for cwp-jdk11, I've got the following error message:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
Makefile:48: recipe for target 'run' failed
make: *** [run] Error 1
```
JAXB is not part of Jenkins anymore since it's going to be detached to a new plugin. This PR pretends to fix the demo

2019-02-11 17:08 UTC, oleg-nenashev approved these changes

2019-02-11 17:08 UTC, oleg-nenashev commented on demo/cwp-jdk11/packager-config.yml
> +      base: "jenkins/jenkins:2.164-jdk11"
All other demos should be probably updated to pin base image versions as well

2019-02-11 20:28 UTC, oleg-nenashev requested changes
TBH I do not think that demos need to be updated to the latest weekly. https://github.com/jenkinsci/jenkinsfile-runner/pull/68#discussion_r255603849 suggests to have fixed versions, that's it. But all other demos in this repo actually have fixed versions. If you update them, it is better to wait till Wednesday and update to 2.150.3

2019-02-12 08:16 UTC, varyvol approved these changes

2019-02-12 08:24 UTC, fcojfernandez commented
@oleg-nenashev I misunderstood your comment. I've updated to the current LTS and once the cwp-jdk11 demo can be updated to a LTS version we can align all the demos

2019-02-12 08:41 UTC, oleg-nenashev approved these changes

2019-02-12 08:42 UTC, merged